services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: inov_assistant
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-assistant-net
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "admin123", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  inov-consulting-ai-assistant:
    build: .
    #image: tizibienvenus/inov-consulting-ai-assistant:latest
    container_name: inov-consulting-ai-assistant
    ports:
      - "8080:8080" 
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env:ro
    #environment:
    #  - MONGO_URI=mongodb://admin:admin123@mongodb:27017/inov_assistant?authSource=admin
    networks:
      - ai-assistant-net
networks:
  ai-assistant-net:
    driver: bridge


volumes:
  mongodb_data: